[package]
name = "mini-opensearch-api"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.2"
rust-stemmers = "1.2.0"
ordered-float = "3.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "2.0.1"
